name: dusdi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy=1.23
  - scikit-image=0.18.1
  - scikit-learn
  - absl-py=0.13.0
  - pyparsing=2.4.7
  - jupyterlab
  - pip:
    - termcolor==1.1.0
    - dm_control==1.0.14
    - dm-env==1.6
    - tensorboard
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.4
    - hydra-core==1.1.0
    - hydra-submitit-launcher==1.1.5
    - pandas==1.3.0
    - ipdb==0.13.9
    - yapf==0.31.0
    - matplotlib==3.7.5
    - opencv-python==4.5.3.56
    - wandb
    - moviepy==1.0.3
    - pygame
    - setuptools==65.5.0
    - gym==0.21.0
    - stable-baselines3==1.6.2
    - einops==0.7.0
